site_name: Open Digital Twin Platform
site_url: https://github.com/odtp-org
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 SDSC / CSFM

# Page tree
nav:
  - Home: index.md
  - Tutorials: 
    - Getting started: tutorials/getting-started.md
    - Users and Digital Twins: tutorials/users-and-digital-twins.md
    - Components and Versions: tutorials/components-and-versions.md
