site_name: Open Digital Twin Platform
site_url: https://github.com/odtp-org
repo_url: https://github.com/odtp-org/odtp
repo_name: odtp-org/odtp
plugins:
  - search
  - link-marker
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
theme:
  name: material
  logo: static/logo/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - content.tooltips
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: amber
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: white
      accent: lime
  custom_dir: overrides
  features:
    - content.tooltips
    - content.footnote.tooltips

markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  &copy; 2023 - 2024 SDSC

# Page tree
nav:
  - Home:
    - Getting started: index.md
    - Introduction: home/index.md
  - Install ODTP:
    - Installation Options: installation/index.md
    - Install with docker compose: installation/docker-compose_install.md
    - Install on a local server: installation/local_server_install.md
  - Tutorials (Use ODTP):
    - Overview: tutorials/index.md
    - Getting started: tutorials/getting-started.md
    - Users: tutorials/users.md
    - Digital Twins: tutorials/digital-twins.md
    - Components and Versions: tutorials/components-and-versions.md
    - Workflows: tutorials/workflows.md
    - Executions: tutorials/executions.md
    - Run Executions: tutorials/run-executions.md
    - Video Tutorials: tutorials/video-tutorials.md
  - Components:
    - Definition: components/index.md
    - Types: components/types.md
    - Develop a component: components/develop.md
    - Run a component: components/run.md
    - Find components: components/find.md
  - Workflows:
    - Overview: workflows/index.md
  - ODTP Orchestrator:
    - Overview: orchestrator/index.md
    - Concept: orchestrator/concept.md
    - Architecture: orchestrator/architecture.md
    - Schema: orchestrator/schema.md
    - Roadmap: orchestrator/roadmap.md
  - ODTP Zoo:
    - Overview: zoo/index.md
    - Add Component: zoo/add-component.md
  - Use Cases:
    - Introduction: usecases/index.md
    - Mobility. Eqasim + Matsim: usecases/mobility-eqasim-matsim.md
    - Mobility. Causal Inference: usecases/mobility-causal-interventions.md
  - Contributing:
    - Overview: contributing/index.md
  - Legal Notice:
    - Acknowledgement: legal/acknowledgement.md
    - Copyright: legal/copyright.md
    - Licensing: legal/licensing.md
    - Disclaimer: legal/disclaimer.md
