site_name: Open Digital Twin Platform
site_url: https://github.com/odtp-org
repo_url: https://github.com/odtp-org/odtp
repo_name: odtp-org/odtp
plugins:
  - search
  - ezglossary
theme:
  name: material
  logo: static/logo/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black 
      accent: amber
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: white
      accent: lime
  custom_dir: overrides  
  features:
    - content.tooltips   

markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
            - includes/abbreviations.md
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format         

copyright: |
  &copy; 2023 - 2024 SDSC

# Page tree
nav:
  - Home:
    - Introduction: index.md
  - ODTP (Orchestrator):
    - Overview: orchestrator/index.md
    - Concepts: orchestrator/concepts.md
    - Architecture: orchestrator/architecture.md
    - Schema: orchestrator/schema.md
    - Roadmap: orchestrator/roadmap.md
    - ODTP Digital Twin: odtp-digital-twin.md
    - ODTP Concepts: odtp-concepts.md    
  - Install ODTP: 
    - Installation Variants: installation/odtp-installation.md
    - Using `docker-compose.yml`: installation/docker-compose.md
    - ODTP local installation: installation/odtp-local-installation.md
    - ODTP third-party services: installation/odtp-third-party-services.md
  - Tutorials (Use ODTP): 
    - Overview: tutorials/index.md 
    - Getting started: tutorials/getting-started.md
    - Users and Digital Twins: tutorials/users-and-digital-twins.md
    - Components and Versions: tutorials/components-and-versions.md
    - Executions: tutorials/executions.md
    - Run Executions: tutorials/run-executions.md
  - ODTP Components:
    - Introduction: components/components-definition.md
    - How to run a component: components/how-to-run-a-component.md
    - How to create a component: components/components-development.md    
  - ODTP Zoo:
    - Introduction: zoo/zoo-definition.md
    - Getting started: zoo/add-component.md
  - Use Cases: 
    - Introduction: use-cases/use-cases.md
    - Mobility. Eqasim + Matsim: use-cases/mobility-eqasim-matsim.md
    - Mobility. Causal Inference: use-cases/mobility-causal-interventions.md
  - Development: 
    - Roadmap: development/roadmap.md
    - Develop a component: components/components-development.md
    - ODTP DB Schema: development/odtp-db-schema.md
  - Glossary:
    - Terms: glossary/terms.md
    - References: glossray/references.md  
  - Legal Notice: 
    - Overview: legal-notice/index.md
    - Acknowledgement: legal-notice/acknowledgement.md
    - Copyright: legal-notice/copyright.md
    - Licensing: legal-notice/licensing.md
    - Disclaimer: legal-notice/disclaimer.md    
